In [1]:
import matplotlib.pyplot as plt
from keras.callbacks import ModelCheckpoint
import pandas as pd
import scipy.io as sio
from os import listdir
from os.path import isfile, join
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout, Conv1D, GlobalAveragePooling1D, MaxPooling1D
from keras import regularizers, layers
from keras.utils import np_utils
import csv

some model's para

In [2]:
number_of_classes = 4
inputsize = 3050
split = 0.9
mypath = 'training2017/'

load data

In [3]:
xdata = [f for f in listdir(mypath) if (isfile(join(mypath, f)) and f[0] == 'A' and f[7] == 'm')]
f = open(mypath+'REFERENCE.csv','r')
reader = csv.reader(f)
ydata = np.array(list(reader))
ydata = ydata[:, 1]
size = len(xdata)
print('Total training size is ', size)

Total training size is  8528


x_set

In [5]:
x_set = np.zeros((size,inputsize))

for i in range(0, size):
    x = sio.loadmat(mypath+xdata[i])['val'][0]
    while(len(x)<inputsize):
            x = np.hstack((x, x))
    x_set[i] = x[:inputsize]
x_set = (x_set - x_set.mean()) / (x_set.std())

x_train = x_set[:, :int(split * size)]
x_val = x_set[:, int(split * size):]

y_set

In [6]:
y_set = np.zeros((size, 1))
for i in range(0, size):
    if ydata[i] == 'N':
        y_set[i] = 0
    elif ydata[i] == 'A':
        y_set[i] = 1
    elif ydata[i] == 'O':
        y_set[i] = 2
    else:
        y_set[i] = 3
y_set = keras.utils.np_utils.to_categorical(y_set)

In [13]:
print(y_set[0:7])

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [81]:
values = [i for i in range(size)]
permutations = np.random.permutation(values)
x_set = x_set[permutations, :]
y_set = y_set[permutations, :]

x_train = x_set[:int(split * size), :]
y_train = y_set[:int(split * size), :]
x_val = x_set[int(split * size):, :]
y_val = y_set[int(split * size):, :]
x_set = x_set[permutations, :]
y_set = y_set[permutations, :]